version: '3'
services:
  # MongoDB service
  mongo:
    image: mongo
    restart: always
    ports:
       - "27017:27017"


  # Node.js service
  # nodejs:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3050:3050"
  #   depends_on:
  #     - mongo
  #   environment:
  #     MONGODB_URI: "mongodb://root:example_password@mongo:27017/todoappdb"
  #     NODE_ENV: development

volumes:
  mongodb_data:
